services:
  redis:
    image: redis
    container_name: ebus_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  redisinsight:
    image: redis/redisinsight
    container_name: ebus_redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis
volumes:
  redis_data:
  redisinsight_data:
